name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - pytest=7.2.2
  - requests==2.31.0
  - fastapi=0.95.2
  - typing_extensions=4.11.0
  - uvicorn==0.22.0
  - gunicorn=22.0.0
  - pip=23.2.1

