name: Python CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda (mamba)
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: fastapi
        environment-file: environment.yml
        auto-activate-base: false
        use-mamba: true
        channels: conda-forge, defaults

    - name: Show env and versions
      run: |
        conda info
        conda list
        python -V
        pip -V
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest test_ml.py -v
